services:
  - type: web
    name: suvidha-one-backend
    env: rust
    plan: free
    rootDir: suvidha-one-backend
    buildCommand: pip install edge-tts && cargo build --release
    startCommand: cargo run --release --bin utility-service
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_PUBLIC_KEY_PEM
        sync: false
      - key: FRONTEND_URLS
        value: https://suvidha-one-frontend.vercel.app
    autoDeploy: true
    healthCheckPath: /health